SELECT USER
FROM DUAL;
--==>> SCOTT


--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR2(30)
, PW    VARCHAR2(20)    NOT NULL
, NAME  VARCHAR2(50)    NOT NULL
, TEL   VARCHAR2(50)    NOT NULL
, EMAIL VARCHAR2(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);


SELECT ID, PW, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;

INSERT INTO TBL_MEMBERLIST(ID,PW,NAME,TEL,EMAIL) VALUES('jangseohyun','1234','장서현','010-1111-1111','test@test.com')
;

SELECT COUNT(*) FROM TBL_MEMBERLIST WHERE TEL='010-1111-1111'
;


COMMIT;

DELETE FROM TBL_MEMBERLIST;